### ISSUE TITLE
url.pathでクエリパラメータが取れない

### ISSUE THREAD

**Issue by yhsmt** [yubessy/urule-scala#2]
https://github.com/yubessy/urule-scala/blob/a350699c87a5cb16eafc3a2152b83c0b39684730/src/main/scala/com/github/yubessy/urule/Matcher.scala#L27

ここのurl.pathが、クエリパラメータを返してくれないみたいなので、

```
- caption: la

  rules:
    - path: '^/inquiry/?\?.*id(?:\[\])?=(?:\d+)'
      category: entry
    - path: '^/inquiry/$'
      category: thanks

  cases:
    - url: http://example.com/inquiry/?id=4868161
      category: entry
```

こんな感じのテストケースが、

```
(uri:,http://example.com/inquiry/?id=4868161)
(category:,None)
(uri.path:,/inquiry/)
(re.regex:,^/inquiry/?\?.*id(?:\[\])?=(?:\d+))
(uri.path:,/inquiry/)
(re.regex:,^/inquiry/$)
(uri:,http://example.com/inquiry/?id=4868161)
(category:,Some(thanks))
```

こんな感じで失敗します。

**Comment by yhsmt** [comment]
`url.toStringRaw`を`split`して従来のフォーマットで取ってくるとか、愚直な対応ではありますが・・・

**Comment by yubessy** [comment]
`params` を使っていただければ解決しないでしょうか？
https://github.com/yubessy/urule-scala/blob/master/src/test/resources/cases.yaml#L75-L87
キャプチャもできるはずです・・・！
https://github.com/yubessy/urule-scala/blob/master/src/test/resources/cases.yaml#L159

**Comment by yhsmt** [comment]
```
- path: '^/inquiry'  
  rules:             
    - params:        
        id[]: '^\d+$'
      category: entry
```

こんな感じで書いたら取れました！　ありがとうございます！
